"""Closed enumerations shared by the simulator, policies and logs."""

from __future__ import annotations

from enum import Enum, IntEnum


class TaskState(str, Enum):
    RAW_BUF = "RAW_BUF"
    PREP_WAIT = "PREP_WAIT"
    PREP_RUN = "PREP_RUN"
    RAW = "RAW"
    LOCAL_WAIT = "LOCAL_WAIT"
    LOCAL_RUN = "LOCAL_RUN"
    ANON_WAIT = "ANON_WAIT"
    ANON_RUN = "ANON_RUN"
    GUARD_WAIT = "GUARD_WAIT"
    GUARD_RUN = "GUARD_RUN"
    ENCODE_WAIT = "ENCODE_WAIT"
    ENCODE_RUN = "ENCODE_RUN"
    READY = "READY"
    UL = "UL"
    EDGE_WAIT = "EDGE_WAIT"
    EDGE_RUN = "EDGE_RUN"
    DL = "DL"
    DONE = "DONE"
    FAIL = "FAIL"

    @property
    def terminal(self) -> bool:
        return self in {TaskState.DONE, TaskState.FAIL}


class Operation(str, Enum):
    PREP = "PREP"
    LOCAL_FER = "LOCAL_FER"
    ANON = "ANON"
    GUARD = "GUARD"
    ENCODE = "ENCODE"
    RSU_INGRESS = "RSU_INGRESS"
    EDGE_FER = "EDGE_FER"
    RSU_MODEL_MAINTENANCE = "RSU_MODEL_MAINTENANCE"


class ResourceKind(str, Enum):
    ACCELERATOR = "accelerator"
    CPU = "cpu"
    ENCODER = "encoder"
    RSU_INGRESS_CPU = "rsu_ingress_cpu"
    RSU_GPU = "rsu_gpu"


class EventPriority(IntEnum):
    COMPLETION = 0
    FAULT_LINK_VERSION_THERMAL = 10
    DEADLINE = 20
    ARRIVAL = 30
    DISPATCH_DECISION = 40


class EventKind(str, Enum):
    ARRIVAL = "ARRIVAL"
    DEADLINE = "DEADLINE"
    COMPUTE_COMPLETE = "COMPUTE_COMPLETE"
    TRANSFER_COMPLETE = "TRANSFER_COMPLETE"
    DEVICE_FAULT = "DEVICE_FAULT"
    LINK_CHANGE = "LINK_CHANGE"
    MODEL_VERSION = "MODEL_VERSION"
    PROFILE_VERSION = "PROFILE_VERSION"
    THERMAL_CHANGE = "THERMAL_CHANGE"
    RSU_SNAPSHOT = "RSU_SNAPSHOT"
    BATTERY_GUARD = "BATTERY_GUARD"
    DISPATCH_DECISION = "DISPATCH_DECISION"


class ActionStage(str, Enum):
    RAW = "RAW"
    READY = "READY"


class ActionKind(str, Enum):
    FAIL = "FAIL"
    LOCAL = "LOCAL"
    PIPE = "PIPE"
    EDGE = "EDGE"


class JobStatus(str, Enum):
    WAITING = "WAITING"
    RUNNING = "RUNNING"
    CANCELLED = "CANCELLED"
    DONE = "DONE"


class TransferDirection(str, Enum):
    UL = "UL"
    DL = "DL"


class TransferStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"
    DONE = "DONE"


class FailureReason(str, Enum):
    NONE = "NONE"
    POLICY_EXPLICIT_FAIL = "POLICY_EXPLICIT_FAIL"
    TIMEOUT = "TIMEOUT"
    BUFFER_CAPACITY = "BUFFER_CAPACITY"
    VEHICLE_CAPACITY = "VEHICLE_CAPACITY"
    BATTERY_GUARD = "BATTERY_GUARD"
    DEVICE_FAULT = "DEVICE_FAULT"
    PREP_FAILED = "PREP_FAILED"
    LOCAL_FAILED = "LOCAL_FAILED"
    ANON_FAILED = "ANON_FAILED"
    ANON_OOM = "ANON_OOM"
    GUARD_REJECTED = "GUARD_REJECTED"
    ENCODE_FAILED = "ENCODE_FAILED"
    ENCODE_SIZE_OOD = "ENCODE_SIZE_OOD"
    UL_FAILED = "UL_FAILED"
    PERMANENT_LINK_LOSS = "PERMANENT_LINK_LOSS"
    ADMISSION_REJECTED = "ADMISSION_REJECTED"
    EDGE_FAILED = "EDGE_FAILED"
    DL_FAILED = "DL_FAILED"
    VERSION_MISMATCH = "VERSION_MISMATCH"
    UNSUPPORTED = "UNSUPPORTED"
    OOD = "OOD"
    INVARIANT = "INVARIANT"


class ReasonCode(str, Enum):
    UNSUPPORTED = "UNSUPPORTED"
    PRIVACY_RISK = "PRIVACY_RISK"
    IDENTITY_SUPPORT = "IDENTITY_SUPPORT"
    EMISSION_SUPPORT = "EMISSION_SUPPORT"
    OOD = "OOD"
    DEVICE_UNSUPPORTED = "DEVICE_UNSUPPORTED"
    JOINT_TRACE_MISSING = "JOINT_TRACE_MISSING"
    PAIRED_MEASUREMENT_MISSING = "PAIRED_MEASUREMENT_MISSING"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"
    VERSION_MISMATCH = "VERSION_MISMATCH"
    PROTOCOL_MISMATCH = "PROTOCOL_MISMATCH"
    MESSAGE_EVIDENCE_MISSING = "MESSAGE_EVIDENCE_MISSING"
    CONNECTIVITY = "CONNECTIVITY"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    SNAPSHOT_CAPACITY = "SNAPSHOT_CAPACITY"
    VEHICLE_CAPACITY = "VEHICLE_CAPACITY"
    VEHICLE_MEMORY = "VEHICLE_MEMORY"
    BATTERY = "BATTERY"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    DEADLINE_IMPOSSIBLE = "DEADLINE_IMPOSSIBLE"
    MODEL_CACHE_MISSING = "MODEL_CACHE_MISSING"
    RSU_CAPACITY = "RSU_CAPACITY"
    STAGE_ILLEGAL = "STAGE_ILLEGAL"
